version: "3.9"
services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=titanic
    volumes:
      - "./green_taxi_postgres:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  ingest_database:
    build: .
    image: ingest_database:dew23
    depends_on:
      - pgdatabase
    restart: on-failure
    
